[project]
name = "superset-cli"
version = "0.3.0"
description = "CLI for self-hosted Apache Superset"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.12"
dependencies = [
  "browser-cookie3>=0.20.1",
  "httpx>=0.28.1",
  "pydantic>=2.11.7",
  "pyyaml>=6.0.2",
  "typer>=0.16.0",
]

[dependency-groups]
dev = [
  "pytest>=8.4.1",
]

[project.urls]
Source = "https://github.com/RobinOnHisOwn/superset_cli"
Issues = "https://github.com/RobinOnHisOwn/superset_cli/issues"

[project.scripts]
superset-cli = "superset_cli.main:main"

[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
pythonpath = ["src"]
